server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teaching_management?useSSL=false&serverTimezone=UTC
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true